server:
  port: 8083

spring:
  application:
    name: bench_oauth_server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    hibernate:
      ddl-auto: update # Automatically creates user & OAuth tables on startup
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
# ------------------------------------------------------------------
# Local Environment Profile
# ------------------------------------------------------------------
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/benchauthDB}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:secretpassword}
    driver-class-name: org.postgresql.Driver

---
# ------------------------------------------------------------------
# Cloud / Render Environment Profile
# ------------------------------------------------------------------
server:
  port: ${PORT:8083} # Render injects PORT dynamically

spring:
  config:
    activate:
      on-profile: render
  datasource:
    # Set these in Render Dashboard -> Environment Variables:
    # SPRING_DATASOURCE_URL, DB_USER, DB_PASSWORD
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dbbenchauth_user:gGzvIUNPR2gy7QGTvC4vHUIBSl40AP8i@dpg-dak3ev142hec73bsfij0-a/dbbenchauth}
    username: ${DB_USER:dbbenchauth_user}
    password: ${DB_PASSWORD:gGzvIUNPR2gy7QGTvC4vHUIBSl40AP8i}
    driver-class-name: org.postgresql.Driver
